publish_interval: 100
settings:
  /arm/angles/commands[0]/actuator_id: {is_repeat: false, max: 0, min: 0}
  /arm/angles/commands[0]/command_type: {is_repeat: false, max: 100, min: 0}
  /arm/angles/commands[0]/command_value: {is_repeat: false, max: 1.0, min: -1.0}
  /arm/angles/commands[1]/actuator_id: {is_repeat: false, max: 1, min: 1}
  /arm/angles/commands[1]/command_type: {is_repeat: false, max: 100, min: 0}
  /arm/angles/commands[1]/command_value: {is_repeat: false, max: 1.0, min: -1.0}
  /arm/angles/commands[2]/actuator_id: {is_repeat: false, max: 2, min: 2}
  /arm/angles/commands[2]/command_type: {is_repeat: false, max: 100, min: 0}
  /arm/angles/commands[2]/command_value: {is_repeat: false, max: 1.0, min: -1.0}
  /arm/angles/commands[3]/actuator_id: {is_repeat: false, max: 3, min: 3}
  /arm/angles/commands[3]/command_type: {is_repeat: false, max: 100, min: 0}
  /arm/angles/commands[3]/command_value: {is_repeat: false, max: 1.0, min: -1.0}
  /arm/angles/commands[4]/actuator_id: {is_repeat: false, max: 4, min: 4}
  /arm/angles/commands[4]/command_type: {is_repeat: false, max: 100, min: 0}
  /arm/angles/commands[4]/command_value: {is_repeat: false, max: 1.0, min: -1.0}
  /arm/angles/commands[5]/actuator_id: {is_repeat: false, max: 5, min: 5}
  /arm/angles/commands[5]/command_type: {is_repeat: false, max: 100, min: 0}
  /arm/angles/commands[5]/command_value: {is_repeat: false, max: 1.0, min: -1.0}
texts: [
  '/arm/angles/commands[0]/actuator_id', '/arm/angles/commands[0]/command_type', '/arm/angles/commands[0]/command_value',
  '/arm/angles/commands[1]/actuator_id', '/arm/angles/commands[1]/command_type', '/arm/angles/commands[1]/command_value',
  '/arm/angles/commands[2]/actuator_id', '/arm/angles/commands[2]/command_type', '/arm/angles/commands[2]/command_value',
  '/arm/angles/commands[3]/actuator_id', '/arm/angles/commands[3]/command_type', '/arm/angles/commands[3]/command_value',
  '/arm/angles/commands[4]/actuator_id', '/arm/angles/commands[4]/command_type', '/arm/angles/commands[4]/command_value',
  '/arm/angles/commands[5]/actuator_id', '/arm/angles/commands[5]/command_type', '/arm/angles/commands[5]/command_value',
]
