CASE:
    controller:
        state:
            type: joint_state_controller/JointStateController
            publish_rate: 50
        velocity:
            left_front_wheel:
                type: velocity_controllers/JointVelocityController
                joint: left_front_wheel
            left_rear_wheel:
                type: velocity_controllers/JointVelocityController
                joint: left_rear_wheel
            right_front_wheel:
                type: velocity_controllers/JointVelocityController
                joint: right_front_wheel
            right_rear_wheel:
                type: velocity_controllers/JointVelocityController
                joint: right_rear_wheel
