CASE:
    hardware_interface:
        loop_hz: 10 # hz
        joints:
            # need to be defined in the order that they run in CAN
            - link_wheel_frontleft
            - link_wheel_backleft
            - link_wheel_frontright
            - link_wheel_backright
